name: intern_practice
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  import_sorter: ^4.6.0
  very_good_analysis: ^5.1.0
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9
  drift: ^2.14.0
  path: ^1.8.3
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.19+1
  drift_dev: ^2.14.1
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
